### ISSUE TITLE
偶尔出现的报错，这是因为异步处理导致的吗？

### ISSUE THREAD

**Issue by tsunami047** [Tuershen/NBTLibrary#1]
`[18:51:46 WARN]: java.lang.IllegalAccessException: Class com.tuershen.nbtlibrary.minecraft.MinecraftItemStack can not access a member of class net.minecraft.server.v1_12_R1.ItemStack with modifiers "private"
[18:51:46 WARN]:        at sun.reflect.Reflection.ensureMemberAccess(Unknown Source)
[18:51:46 WARN]:        at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(Unknown Source)
[18:51:46 WARN]:        at java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
[18:51:46 WARN]:        at java.lang.reflect.Field.set(Unknown Source)
[18:51:46 WARN]:        at com.tuershen.nbtlibrary.minecraft.MinecraftItemStack.set(MinecraftItemStack.java:66)
[18:51:46 WARN]:        at com.tuershen.nbtlibrary.minecraft.MinecraftItemStack.setMinecraftItemStackTag(MinecraftItemStack.java:52)
[18:51:46 WARN]:        at com.tuershen.nbtlibrary.minecraft.PluginManager.setCompound(PluginManager.java:19)
[18:51:46 WARN]:        at git.tsunami047.tintensify.baoshi.BConfigHandler.buildMythicItemUnbind(BConfigHandler.java:267)
[18:51:46 WARN]:        at git.tsunami047.tintensify.baoshi.BConfigHandler.lambda$null$4(BConfigHandler.java:327)
[18:51:46 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
[18:51:46 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
[18:51:46 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[18:51:46 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[18:51:46 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[18:51:46 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)`
不知道怎么修

**Comment by tsunami047** [comment]
MinecraftItemStack类里面的成员为什么Field类型那两个变量是静态的，多线程下可能某个一个方法刚刚get之后，还没有设置访问权限，另一个方法就进行使用了，导致报错。去掉static就好了。这个本身也是可以复用的。
